-- Create table for site content management
CREATE TABLE IF NOT EXISTS site_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  subtitle TEXT,
  content TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Public can view site content" ON site_content;
CREATE POLICY "Public can view site content" ON site_content
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin can manage site content" ON site_content;
CREATE POLICY "Admin can manage site content" ON site_content
  FOR ALL USING (true);

-- Insert initial data for Cultural Heritage section
INSERT INTO site_content (section_key, title, subtitle, content)
VALUES (
  'cultural_heritage',
  'Kültürel Mirasımız',
  'Geleneksel Oyunlarımızı Yaşatıyoruz',
  'Geleneksel Türk oyunları, yüzyıllardır nesilden nesile aktarılan kültürel mirasımızın önemli bir parçasıdır. Teknolojinin hızla geliştiği günümüzde, bu geleneksel oyunları dijital ortamda belgeleyerek gelecek nesillere aktarmak ve yaşatmak istiyoruz.'
) ON CONFLICT (section_key) DO NOTHING;
