-- =====================================================
-- Ücretsiz oyunlar (GamerPower API → Supabase cache)
-- Supabase SQL Editor'da çalıştırın
-- =====================================================

CREATE TABLE IF NOT EXISTS free_games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  image TEXT,
  platform TEXT,
  worth TEXT,
  end_date TEXT,
  open_giveaway_url TEXT NOT NULL,
  giveaway_type TEXT DEFAULT 'Game',
  description TEXT,
  is_active BOOLEAN DEFAULT true NOT NULL,
  synced_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_free_games_active ON free_games(is_active, synced_at DESC);
CREATE INDEX IF NOT EXISTS idx_free_games_end ON free_games(end_date);

CREATE TABLE IF NOT EXISTS free_games_sync_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'success',
  synced_count INT DEFAULT 0,
  message TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE free_games ENABLE ROW LEVEL SECURITY;
ALTER TABLE free_games_sync_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "free_games_public_read" ON free_games;
DROP POLICY IF EXISTS "free_games_admin_write" ON free_games;
DROP POLICY IF EXISTS "free_games_sync_log_read" ON free_games_sync_log;
DROP POLICY IF EXISTS "free_games_sync_log_write" ON free_games_sync_log;

CREATE POLICY "free_games_public_read" ON free_games
  FOR SELECT USING (true);

CREATE POLICY "free_games_admin_write" ON free_games
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "free_games_sync_log_read" ON free_games_sync_log
  FOR SELECT USING (true);

CREATE POLICY "free_games_sync_log_write" ON free_games_sync_log
  FOR ALL USING (true) WITH CHECK (true);

GRANT SELECT ON free_games TO anon, authenticated;
GRANT ALL ON free_games TO anon, authenticated;
GRANT SELECT, INSERT ON free_games_sync_log TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE free_games_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE free_games_sync_log_id_seq TO anon, authenticated;

NOTIFY pgrst, 'reload schema';

-- Opsiyonel: Perşembe 18:00 TR (15:00 UTC) otomatik senkron
-- 1) Dashboard → Database → Extensions → pg_cron + pg_net açın
-- 2) Edge Function deploy: supabase functions deploy sync-free-games
-- 3) Aşağıdaki cron job'u URL ve service role key ile güncelleyin:
--
-- SELECT cron.schedule(
--   'sync-free-games-weekly',
--   '0 15 * * 4',
--   $$
--   SELECT net.http_post(
--     url := 'https://YOUR_PROJECT.supabase.co/functions/v1/sync-free-games',
--     headers := jsonb_build_object(
--       'Authorization', 'Bearer YOUR_SERVICE_ROLE_KEY',
--       'Content-Type', 'application/json'
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );
