-- İletişim formundan gelen mesajları saklamak için tablo
CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS etkinleştir
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- Herkes form gönderebilir (INSERT)
DROP POLICY IF EXISTS "Anyone can submit contact form" ON contact_messages;
CREATE POLICY "Anyone can submit contact form" ON contact_messages
  FOR INSERT WITH CHECK (true);

-- Herkes okuyabilir (admin paneli için - daha güvenli yapmak istersen auth ekleyebilirsin)
DROP POLICY IF EXISTS "Allow read contact messages" ON contact_messages;
CREATE POLICY "Allow read contact messages" ON contact_messages
  FOR SELECT USING (true);

-- Güncelleme (okundu işareti için)
DROP POLICY IF EXISTS "Allow update contact messages" ON contact_messages;
CREATE POLICY "Allow update contact messages" ON contact_messages
  FOR UPDATE USING (true);

-- Silme (spam temizleme için)
DROP POLICY IF EXISTS "Allow delete contact messages" ON contact_messages;
CREATE POLICY "Allow delete contact messages" ON contact_messages
  FOR DELETE USING (true);

-- İndeks: tarihe göre sıralama
CREATE INDEX IF NOT EXISTS idx_contact_messages_created_at ON contact_messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contact_messages_is_read ON contact_messages(is_read);
