-- =====================================================
-- HABERLER — Oyun dünyası haberleri
-- Supabase SQL Editor'da çalıştırın
-- =====================================================

CREATE TABLE IF NOT EXISTS news_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  excerpt TEXT,
  subtitle TEXT,
  content TEXT NOT NULL DEFAULT '',
  cover_image TEXT,
  category TEXT DEFAULT 'Oyun Dünyası',
  tags TEXT[] DEFAULT '{}',
  related_game_id BIGINT REFERENCES games(id) ON DELETE SET NULL,
  author TEXT DEFAULT 'Kuralı Ne?',
  author_avatar TEXT,
  seo_title TEXT,
  seo_description TEXT,
  read_time_minutes INT DEFAULT 1,
  view_count INT DEFAULT 0 NOT NULL,
  is_published BOOLEAN DEFAULT false,
  is_featured BOOLEAN DEFAULT false,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_news_posts_slug ON news_posts(slug);
CREATE INDEX IF NOT EXISTS idx_news_posts_published ON news_posts(is_published, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_posts_featured ON news_posts(is_featured) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_news_posts_category ON news_posts(category);

ALTER TABLE news_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view published news" ON news_posts;
CREATE POLICY "Public can view published news" ON news_posts
  FOR SELECT USING (is_published = true);

DROP POLICY IF EXISTS "Allow all for news_posts" ON news_posts;
CREATE POLICY "Allow all for news_posts" ON news_posts
  FOR ALL USING (true);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'update_updated_at_column') THEN
    DROP TRIGGER IF EXISTS update_news_posts_updated_at ON news_posts;
    CREATE TRIGGER update_news_posts_updated_at
      BEFORE UPDATE ON news_posts
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION increment_news_view(post_slug TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE news_posts
  SET view_count = COALESCE(view_count, 0) + 1
  WHERE slug = post_slug AND is_published = true;
END;
$$;

GRANT EXECUTE ON FUNCTION increment_news_view(TEXT) TO anon, authenticated;
