-- =====================================================
-- HABERLER — Emoji reaksiyonları + yorumlar
-- Supabase SQL Editor'da çalıştırın (news_posts tablosu sonrası)
-- =====================================================

-- Yorumlar
CREATE TABLE IF NOT EXISTS news_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  news_post_id BIGINT NOT NULL REFERENCES news_posts(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  author_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  avatar_url TEXT,
  content TEXT NOT NULL,
  likes INT DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_news_comments_post ON news_comments(news_post_id, created_at DESC);

-- Emoji reaksiyonları (haber başına ziyaretçi başına 1 reaksiyon)
CREATE TABLE IF NOT EXISTS news_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  news_post_id BIGINT NOT NULL REFERENCES news_posts(id) ON DELETE CASCADE,
  emoji TEXT NOT NULL CHECK (char_length(emoji) <= 8),
  visitor_key TEXT NOT NULL,
  visitor_type TEXT NOT NULL DEFAULT 'guest' CHECK (visitor_type IN ('user', 'guest')),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (news_post_id, visitor_key)
);

CREATE INDEX IF NOT EXISTS idx_news_reactions_post ON news_reactions(news_post_id);

-- RLS
ALTER TABLE news_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE news_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "news_comments_select" ON news_comments;
DROP POLICY IF EXISTS "news_comments_insert" ON news_comments;
DROP POLICY IF EXISTS "news_comments_update" ON news_comments;
DROP POLICY IF EXISTS "news_comments_delete" ON news_comments;

CREATE POLICY "news_comments_select" ON news_comments FOR SELECT USING (true);
CREATE POLICY "news_comments_insert" ON news_comments FOR INSERT WITH CHECK (true);
CREATE POLICY "news_comments_update" ON news_comments FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "news_comments_delete" ON news_comments FOR DELETE USING (true);

DROP POLICY IF EXISTS "news_reactions_select" ON news_reactions;
DROP POLICY IF EXISTS "news_reactions_insert" ON news_reactions;
DROP POLICY IF EXISTS "news_reactions_update" ON news_reactions;
DROP POLICY IF EXISTS "news_reactions_delete" ON news_reactions;

CREATE POLICY "news_reactions_select" ON news_reactions FOR SELECT USING (true);
CREATE POLICY "news_reactions_insert" ON news_reactions FOR INSERT WITH CHECK (true);
CREATE POLICY "news_reactions_update" ON news_reactions FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "news_reactions_delete" ON news_reactions FOR DELETE USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON news_comments TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON news_reactions TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE news_comments_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE news_reactions_id_seq TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
