-- =====================================================
-- KATEGORİLER TABLOSU - Admin panelinden yönetilebilir
-- =====================================================
-- NOT: games.category TEXT olarak kalıyor (foreign key değil)
-- Bu sayede kategori silmek oyunları bozmaz
-- =====================================================

-- 1. Tablo oluştur
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  image_url TEXT,
  color TEXT DEFAULT 'gray' CHECK (color IN ('red', 'orange', 'purple', 'blue', 'green', 'indigo', 'gray')),
  order_index INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. İndeksler
CREATE INDEX IF NOT EXISTS idx_categories_order ON categories(order_index);
CREATE INDEX IF NOT EXISTS idx_categories_name ON categories(name);
CREATE INDEX IF NOT EXISTS idx_categories_active ON categories(is_active);

-- 3. RLS Politikaları
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view categories" ON categories;
CREATE POLICY "Public can view categories" ON categories
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow all for categories" ON categories;
CREATE POLICY "Allow all for categories" ON categories
  FOR ALL USING (true);

-- 4. Otomatik updated_at trigger'ı (eğer fonksiyon varsa kullan)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'update_updated_at_column') THEN
    DROP TRIGGER IF EXISTS update_categories_updated_at ON categories;
    CREATE TRIGGER update_categories_updated_at 
      BEFORE UPDATE ON categories
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END
$$;

-- 5. Kategori adı değiştiğinde oyunları da güncelle (CASCADE)
CREATE OR REPLACE FUNCTION sync_category_name_to_games()
RETURNS TRIGGER AS $$
BEGIN
  -- Sadece isim değiştiyse güncelle
  IF OLD.name IS DISTINCT FROM NEW.name THEN
    UPDATE games SET category = NEW.name WHERE category = OLD.name;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sync_category_name ON categories;
CREATE TRIGGER sync_category_name
  AFTER UPDATE ON categories
  FOR EACH ROW EXECUTE FUNCTION sync_category_name_to_games();

-- 6. Varsayılan kategorileri ekle
INSERT INTO categories (name, description, image_url, color, order_index) VALUES
  ('Kağıt Oyunları', 'İskambil kağıtlarıyla oynanan klasik ve modern kart oyunları.', 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?q=80&w=2070&auto=format&fit=crop', 'red', 1),
  ('Masa Oyunları', 'Masa başında arkadaşlarınızla veya ailenizle oynayabileceğiniz strateji ve şans oyunları.', 'https://images.unsplash.com/photo-1611195974226-a6a9be9dd763?q=80&w=2000&auto=format&fit=crop', 'purple', 2),
  ('Kutu Oyunları', 'Zar, piyon ve kartlarla oynanan eğlenceli kutu oyunları.', 'https://images.unsplash.com/photo-1563906267088-b029e7101114?q=80&w=2070&auto=format&fit=crop', 'orange', 3),
  ('Zeka Oyunları', 'Zihninizi zorlayacak, düşünme becerilerinizi geliştirecek strateji oyunları.', 'https://images.unsplash.com/photo-1580541832626-2a7131ee809f?q=80&w=2070&auto=format&fit=crop', 'indigo', 4),
  ('Dış Mekan', 'Açık havada, parkta veya bahçede oynayabileceğiniz en eğlenceli oyunlar.', 'https://images.unsplash.com/photo-1551966775-a4ddc8df052b?q=80&w=2070&auto=format&fit=crop', 'green', 5),
  ('İç Mekan', 'Evde, sınıfta veya kapalı alanlarda oynanabilecek keyifli oyunlar.', 'https://images.unsplash.com/photo-1560420025-9a327c4418d4?q=80&w=1974&auto=format&fit=crop', 'blue', 6)
ON CONFLICT (name) DO NOTHING;

-- 7. Mevcut oyunların kategorilerini standartlaştır (ilk kurulumda bir kez çalışır)
UPDATE games SET category = 'Dış Mekan' WHERE category ILIKE 'dış mekan' OR category ILIKE 'dis mekan';
UPDATE games SET category = 'İç Mekan' WHERE category ILIKE 'iç mekan' OR category ILIKE 'ic mekan';
UPDATE games SET category = 'Kağıt Oyunları' WHERE category ILIKE 'kağıt oyunları' OR category ILIKE 'kagit oyunlari';
UPDATE games SET category = 'Masa Oyunları' WHERE category ILIKE 'masa oyunları' OR category ILIKE 'masa oyunlari';
UPDATE games SET category = 'Kutu Oyunları' WHERE category ILIKE 'kutu oyunları' OR category ILIKE 'kutu oyunlari';
UPDATE games SET category = 'Zeka Oyunları' WHERE category ILIKE 'zeka oyunları' OR category ILIKE 'zeka oyunlari';
UPDATE games SET category = TRIM(category);
