-- =====================================================
-- HABERLER — Tam kurulum / onarım (400 hatası için)
-- Supabase Dashboard → SQL Editor → Run
-- =====================================================

-- 1) Tablo yoksa oluştur (minimal)
CREATE TABLE IF NOT EXISTS news_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT NOT NULL DEFAULT '',
  cover_image TEXT,
  category TEXT DEFAULT 'Oyun Dünyası',
  tags TEXT[] DEFAULT '{}',
  author TEXT DEFAULT 'Kuralı Ne?',
  is_published BOOLEAN DEFAULT false,
  is_featured BOOLEAN DEFAULT false,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2) Eksik kolonları ekle (eski kurulumlar için)
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS subtitle TEXT;
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS author_avatar TEXT;
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS read_time_minutes INT DEFAULT 1;
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS view_count INT DEFAULT 0;
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS related_game_id BIGINT;

-- view_count NOT NULL (mevcut null satırları düzelt)
UPDATE news_posts SET view_count = 0 WHERE view_count IS NULL;
ALTER TABLE news_posts ALTER COLUMN view_count SET DEFAULT 0;
ALTER TABLE news_posts ALTER COLUMN view_count SET NOT NULL;

-- FK — games tablosu varsa bağla
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'games') THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints
      WHERE constraint_name = 'news_posts_related_game_id_fkey'
        AND table_name = 'news_posts'
    ) THEN
      ALTER TABLE news_posts
        ADD CONSTRAINT news_posts_related_game_id_fkey
        FOREIGN KEY (related_game_id) REFERENCES games(id) ON DELETE SET NULL;
    END IF;
  END IF;
END $$;

-- 3) İndeksler
CREATE INDEX IF NOT EXISTS idx_news_posts_slug ON news_posts(slug);
CREATE INDEX IF NOT EXISTS idx_news_posts_published ON news_posts(is_published, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_posts_featured ON news_posts(is_featured) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_news_posts_category ON news_posts(category);
CREATE INDEX IF NOT EXISTS idx_news_posts_views ON news_posts(view_count DESC) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_news_posts_trending ON news_posts(is_published, published_at DESC, view_count DESC);

-- 4) RLS — admin panel anon key ile yazabilsin
ALTER TABLE news_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view published news" ON news_posts;
DROP POLICY IF EXISTS "Allow all for news_posts" ON news_posts;
DROP POLICY IF EXISTS "news_posts_select_published" ON news_posts;
DROP POLICY IF EXISTS "news_posts_select_all" ON news_posts;
DROP POLICY IF EXISTS "news_posts_insert" ON news_posts;
DROP POLICY IF EXISTS "news_posts_update" ON news_posts;
DROP POLICY IF EXISTS "news_posts_delete" ON news_posts;

-- Herkes yayınlanmış haberleri okuyabilir
CREATE POLICY "news_posts_select_published" ON news_posts
  FOR SELECT USING (is_published = true);

-- Admin / anon insert-update-delete (site admin paneli anon key kullanıyor)
CREATE POLICY "news_posts_insert" ON news_posts
  FOR INSERT WITH CHECK (true);

CREATE POLICY "news_posts_update" ON news_posts
  FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "news_posts_delete" ON news_posts
  FOR DELETE USING (true);

-- Admin listesi için taslakları da görmek üzere (authenticated/anon SELECT all)
CREATE POLICY "news_posts_select_all" ON news_posts
  FOR SELECT USING (true);

-- 5) Yetkiler
GRANT SELECT, INSERT, UPDATE, DELETE ON news_posts TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- 6) updated_at trigger
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'update_updated_at_column') THEN
    DROP TRIGGER IF EXISTS update_news_posts_updated_at ON news_posts;
    CREATE TRIGGER update_news_posts_updated_at
      BEFORE UPDATE ON news_posts
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

-- 7) Görüntülenme sayacı
CREATE OR REPLACE FUNCTION increment_news_view(post_slug TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE news_posts
  SET view_count = COALESCE(view_count, 0) + 1
  WHERE slug = post_slug AND is_published = true;
END;
$$;

GRANT EXECUTE ON FUNCTION increment_news_view(TEXT) TO anon, authenticated;

-- PostgREST şema önbelleğini yenile
NOTIFY pgrst, 'reload schema';
