-- Create table for game gallery images
CREATE TABLE IF NOT EXISTS game_gallery_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT REFERENCES games(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  caption TEXT,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE game_gallery_images ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Public can view gallery images" ON game_gallery_images;
CREATE POLICY "Public can view gallery images" ON game_gallery_images
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin can manage gallery images" ON game_gallery_images;
CREATE POLICY "Admin can manage gallery images" ON game_gallery_images
  FOR ALL USING (true);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_game_gallery_game_id ON game_gallery_images(game_id);
