
-- Create table for Game of the Day selection
CREATE TABLE IF NOT EXISTS daily_game_selection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT REFERENCES games(id) ON DELETE CASCADE,
  custom_title TEXT,
  custom_description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE daily_game_selection ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public can view active daily game" ON daily_game_selection
  FOR SELECT USING (is_active = true);

CREATE POLICY "Admin can manage daily game" ON daily_game_selection
  FOR ALL USING (true);

-- Insert a dummy initial record if needed (optional)
-- INSERT INTO daily_game_selection (game_id, custom_title, custom_description) 
-- SELECT id, 'Günün Oyunu', 'Bugün sizin için seçtiğimiz özel oyun!' 
-- FROM games LIMIT 1;
