-- Önce varsa eski tabloyu temizle (Hata almamak için)
DROP TABLE IF EXISTS daily_game_selection;

-- 1. Tabloyu Oluştur
CREATE TABLE daily_game_selection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT REFERENCES games(id) ON DELETE CASCADE,
  custom_title TEXT,
  custom_description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Güvenlik Politikalarını (RLS) Aç
ALTER TABLE daily_game_selection ENABLE ROW LEVEL SECURITY;

-- 3. Okuma ve Yazma İzinlerini Tanımla
CREATE POLICY "Public can view active daily game" ON daily_game_selection
  FOR SELECT USING (is_active = true);

CREATE POLICY "Admin can manage daily game" ON daily_game_selection
  FOR ALL USING (true);

-- 4. İlk Veriyi Ekle (Rastgele bir oyun)
INSERT INTO daily_game_selection (game_id, custom_title, custom_description, is_active)
SELECT id, 'Günün Oyunu: ' || name, 'Bugün sizin için seçtiğimiz özel oyun! Hemen kuralları öğrenin ve oynamaya başlayın.', true
FROM games
ORDER BY random()
LIMIT 1;
